### ISSUE TITLE
suggestions: using latexdiffcite just to add in-text citations

### ISSUE THREAD

**Issue by jonbaron1944** [cmeeren/latexdiffcite#6]
It seems that latexdiffcite - along with its many other good features - is the only way to get in-text citations into a tex file, e.g., replacing "\cite{Baron16}" with "Baron (2016)" or something like that. I just compare a file with itself. (This does not always work, and I'm trying to figure out why not.) I need this because I edit and produce an open-access journal (with no author fees), which publishes in pdf and html. The production involves creation of a tex file, usually from Word. But some authors submit tex, and most of them use bibtex. To make the html, I use hevea. It does handle bibtex, but it does not insert author, date, which is the style I need (APA style), so I have to make the tex file include the citations before conversion to html.

It would be very nice if you had an option to output just this file, with the citations fixed and nothing else. It could in principle work with a single input file, but it is not difficult to make a copy first. It would also be nice if the new citations were not listed with \ldiffentity{}. (I think I can get around that by simply defining it as doing nothing, but I haven't tried.)

A second minor issue is that most authors who do use bibtex will use apacite, not natbib. I'm trying to revise my .latexdiffcite.json file to handle apacite, so I may be able to handle this myself, but if you happen to know someone who has done this it would be nice to include it with the examples. If I get it done I will send you the result, but don't hold your breath!

**Comment by cmeeren** [comment]
Thank you for the feedback. Unfortunately I will not implement the feature you requested, since it is outside the scope of latexdiffcite.

IIRC `ldiffentity{}` is completely optional, just create a configuration file without it.
